/**
 * Build script: generates firebase-config.js from Netlify environment variables.
 * Runs automatically during Netlify deploy via netlify.toml [build] command.
 *
 * Usage (local): node build-config.js
 * (Set env vars in your shell first, or use a .env file with dotenv)
 */

const fs = require('fs');
const path = require('path');

const required = [
    'FIREBASE_API_KEY',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID',
];

const missing = required.filter(key => !process.env[key]);
if (missing.length > 0) {
    console.error('❌ Missing required environment variables:\n  ' + missing.join('\n  '));
    process.exit(1);
}

const config = `// Auto-generated by build-config.js — DO NOT EDIT
// This file is gitignored. Source of truth: Netlify env vars.
window.FIREBASE_CONFIG = {
    apiKey: "${process.env.FIREBASE_API_KEY}",
    authDomain: "${process.env.FIREBASE_AUTH_DOMAIN}",
    projectId: "${process.env.FIREBASE_PROJECT_ID}",
    storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
    appId: "${process.env.FIREBASE_APP_ID}",
    measurementId: "${process.env.FIREBASE_MEASUREMENT_ID || ''}"
};
`;

const outputPath = path.join(__dirname, 'firebase-config.js');
fs.writeFileSync(outputPath, config, 'utf8');
console.log('✅ firebase-config.js generated from environment variables.');
